import {defaultState} from './data.js';import {uid} from './utils/format.js';
const LEGACY_KEYS=['orlando_trip_planner','magic_trip_dashboard','orlando-planner','orlandoTripPlanner'];
export function discoverLegacy(){for(const key of LEGACY_KEYS){try{const raw=localStorage.getItem(key);if(raw)return {key,data:JSON.parse(raw)}}catch{}}return null}
export function migrateLegacy(old){const next=defaultState(),report={shopping:0,expenses:0,days:0,items:0,warnings:[]};const src=old?.data||old||{};next.trip={...next.trip,...(src.trip||{}),...(src.settings?{name:src.settings.tripName||next.trip.name,startDate:src.settings.startDate||next.trip.startDate,endDate:src.settings.endDate||next.trip.endDate,currency:src.settings.currency||next.trip.currency}:{})};
 for(const x of src.shopping||[]){next.purchases.push({id:x.id||uid('purchase'),name:x.name||'Compra migrada',description:'',category:x.category||'Outros',priority:x.priority||'media',quantity:1,locationType:x.outlet?'outlet':'park',parkId:x.park||null,outletId:x.outlet||null,storeName:x.store||'',estimatedUnitValue:Number(x.value)||0,estimatedTotalValue:Number(x.value)||0,paidUnitValue:null,paidTotalValue:null,currency:next.trip.currency,paymentMethod:'',status:x.status==='comprado'?'comprado':(x.status||'desejado'),purchaseDate:'',imageUrl:x.image||'',imagePath:'',notes:x.note||'',recordType:'purchase',createdAt:new Date().toISOString()});report.shopping++}
 for(const e of src.expenses||[]){const match=next.purchases.find(p=>p.status==='comprado'&&Math.abs(p.estimatedTotalValue-Number(e.value||0))<.01&&p.name.toLowerCase().includes(String(e.desc||'').replace(/^Compra:\s*/i,'').toLowerCase()));if(match){match.paidTotalValue=Number(e.value)||0;match.paymentMethod=e.pay||'';match.purchaseDate=e.date||''}else{next.purchases.push({id:e.id||uid('expense'),name:e.desc||'Despesa migrada',category:e.category||'Outros',quantity:1,locationType:e.outlet?'outlet':'park',parkId:e.park||null,outletId:e.outlet||null,estimatedTotalValue:Number(e.value)||0,paidTotalValue:Number(e.value)||0,currency:next.trip.currency,paymentMethod:e.pay||'',status:'comprado',purchaseDate:e.date||'',notes:e.note||'',recordType:'expense',createdAt:new Date().toISOString()});report.expenses++}}
 for(const d of src.itinerary||[]){const day={id:d.id||uid('day'),name:d.day||d.name||'Dia',date:d.date||'',destinationType:d.park==='compras'?'outlet':'park',parkId:d.park==='compras'?null:(d.park||null),outletId:d.outlet||null,startTime:d.start||'',endTime:d.end||'',notes:d.note||'',order:next.itineraryDays.length};next.itineraryDays.push(day);report.days++;for(const i of d.items||[]){next.itineraryItems.push({id:i.id||uid('item'),dayId:day.id,type:i.type||'manual',title:i.name||i.title||'Atividade',parkId:i.park||day.parkId,outletId:i.outlet||null,time:i.time||'',durationMinutes:Number(i.duration)||0,status:i.done?'concluido':'pendente',notes:i.note||'',order:next.itineraryItems.length});report.items++}}
 return {state:next,report}}
export function downloadMigrationReport(report){const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='relatorio-migracao-v2.json';a.click();URL.revokeObjectURL(a.href)}
